# Generated by Django 6.0.6 on 2026-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
