# Generated by Django 6.0.6 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_prep_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
